Traceback (most recent call last):
  File "d:\checkinfour\CheckFour\FourInRow\DQN_Trainer_Opp.py", line 81, in <module>
    main()
  File "d:\checkinfour\CheckFour\FourInRow\DQN_Trainer_Opp.py", line 37, in main
    Q = player1.DQN
        ^^^^^^^^^^^
AttributeError: 'Random_Agent' object has no attribute 'DQN'
